### PR TITLE
F/quiz

### PR DESCRIPTION
**Pull request by s3745409**
Please test the below. If everything is ok, please merge into main-dev.

NOTE: Because these are integrated with Ethereum now, submissions are final. Remigrating Ethereum smart contracts will not work. Only way is to create a new enrolment for a different course via Database.

When a micro cred has been submitted user is redirected back to dashboard. Submitted module now appears in completed section.

When a course is completed, it is no longer accessible.

image

Student is able to submit their micro-credential at any time. All they have to do is click the submit button at the bottom to the table.

image

Before submission, user is prompted again to confirm that they want to submit. This is done to prevent accidental clicking of submit button.

image

Quiz page is same as before, only difference is that the attempt number appears at the top.

image

As always, if you have issues let me know.

### CODE REVIEW

**Review by shreyasamanta — APPROVED** [review]
Looks good to me, taking a long time to process requests but that is to be expected.
Great work!

**Review by jacktswallow — COMMENTED** [review]
Ran into a couple of issues:

- Both the submit buttons for a quiz and for microcred allow you to click them rapidly and give no loading indication, leading me to press them multiple times thinking they weren't working, which causes the backend to be triggered once for every click. This leads to the submission being made multiple times, and then causes the front end to display the data incorrectly as it returns before the final backend call has completed. I would suggest that these buttons need to either go to a redirect loading page or disable the submit button and give a loading indication. 
- There was also an issue where after submitting the microcred, it returned me to the homepage but the entire page was greyed out and disabled. Refreshing fixed this.

Other than these issues everything was great and worked as expected.

**Comment by s3745409** [comment]
@jacktswallow Buttons and content has been replaced by a message once a submission event has occurred.

Placed a message once quiz has been submitted.

image

Placed message when submitting micro credential.

image

Dismiss event when you click the submit button in the modal was not being triggered which is why there was a grey screen. This has now been fixed.

**Review by jacktswallow — APPROVED** [review]
All the previously mentioned issues have been fixed, everything is working as expected.

**Pull request merged**
