### PR TITLE
F/module attempts

### PR DESCRIPTION
**Pull request by jacktswallow**

### CODE REVIEW

**Review by shreyparekh — APPROVED** [review]

**Comment by shreyasamanta** [comment]
If a module attempt is made with the student answering 0 questions and clicking submit, trying to view the student's attempt for that  module results in an error.
image

**Comment by jacktswallow** [comment]
> If a module attempt is made with the student answering 0 questions and clicking submit, trying to view the student's attempt for that module results in an error.
> image

That is strange, just tested it on my local and I'm not having that issue. From that error though, I think it may be due to selectedModule being index 0, so 0-1=-1. 
Decided to test that theory and selected 'Select a module' (which is index 0) which caused it to crash with a similar issue. Thinking I'll try disabling 'Select a module' as a selectable option.

**Comment by jacktswallow** [comment]
Just added a fix for that issue, @shreyasamanta if you could try again and see if you're still getting the error, that would be great, thanks!

**Comment by shreyasamanta** [comment]
Still happening :\ it happens after I select a module which contains an attempt with unanswered questions, doesn't seem to be an issue with the select a module option.

Also I can't get it to display any attempts at all, shows 'no attempts for module' even if there is one. Looking at the console it seems to be fetching the data correctly, so not sure whats happening.
image


You might need to open the app in Chrome to recreate the issues

**Review by shreyasamanta — APPROVED** [review]

**Review by s3745409 — APPROVED** [review]
Works as expected - no longer getting the crash screen when trying to view a student attempt. Tested in Brave (Chromium) and Firefox

image

**Pull request merged**
